describe('Prueba crear cuenta e2e', function() {
  it('Crea cuenta CI-Chile', function() {
    cy.visit('http://127.0.0.1:8000/account/create')
    cy.url().should('include', '/account/create')
    cy.get('input#id_first_name.textinput.textInput.form-control')
      .type('Ignacio')
      cy.get('input#id_last_name.textinput.textInput.form-control')
      .type('Balart')
      cy.get('input#id_username.textinput.textInput.form-control')
      .type('ibalart2')
      cy.get('input#id_password1.textinput.textInput.form-control')
      .type('unab2020')
      cy.get('input#id_password2.textinput.textInput.form-control')
      .type('unab2020')
      cy.get('input#id_email.emailinput.form-control')
      .type('ignacio.balart1@gmail.com')
      cy.get('button.btn.btn-secondary').click()
      cy.visit('http://127.0.0.1:8000/account/signin')
      cy.get('input#id_username.textinput.textInput.form-control')
      .type('ibalart2')
      cy.get('input#id_password.textinput.textInput.form-control')
      .type('unab2020')
      cy.get('button.btn.btn-secondary').click()
  })
})