# Generated by Django 3.1.2 on 2020-12-02 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car_brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='car_brand')),
                ('code', models.IntegerField()),
            ],
            options={
                'verbose_name': 'car_brand',
                'verbose_name_plural': 'car_brands',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='campitble_models',
            field=models.JSONField(default='[]'),
        ),
        migrations.CreateModel(
            name='Car_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('code', models.IntegerField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.car_brand')),
            ],
            options={
                'verbose_name': 'car_model',
                'verbose_name_plural': 'car_models',
                'ordering': ('name',),
            },
        ),
    ]
