# Generated by Django 3.1.2 on 2020-12-02 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20201201_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='campitble_models',
            field=models.JSONField(default='list'),
        ),
    ]
