# Generated by Django 3.1.2 on 2020-12-02 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20201201_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='campitble_models',
        ),
        migrations.AddField(
            model_name='product',
            name='compatible_models',
            field=models.TextField(blank=True),
        ),
    ]
